### PR TITLE
better aliasing for c long/unsigned long

### LINKED ISSUE #73: RangeWrapper causing segfault on raspberry pi
```d
void main()
{
	writeln("A");
	py_init();
	writeln("B");
	module_init();
	writeln("C");

	PyEval_InitThreads();
}
```

when commenting out the init_rangewrapper function it seems to work, otherwise it segfaults:

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
A

Program received signal SIGSEGV, Segmentation fault.
strlen () at ../sysdeps/arm/armv6/strlen.S:26
26	../sysdeps/arm/armv6/strlen.S: No such file or directory.
(gdb) bt
#0  strlen () at ../sysdeps/arm/armv6/strlen.S:26
#1  0x76d71e28 in PyString_FromString () from /usr/lib/arm-linux-gnueabihf/libpython2.7.so.1.0
#2  0x76d02d44 in PyDict_GetItemString () from /usr/lib/arm-linux-gnueabihf/libpython2.7.so.1.0
#3  0x76d37dec in PyType_Ready () from /usr/lib/arm-linux-gnueabihf/libpython2.7.so.1.0
#4  0x0005bdc0 in pyd.class_wrap._wrap_class!(pyd.make_object.RangeWrapper, "RangeWrapper", "", "pyd", pyd.class_wrap.Def!(pyd.make_object.RangeWrapper.iter(), pyd.def.PyName!("__iter__").PyName).Def, pyd.class_wrap.Def!(pyd.make_object.RangeWrapper.next()).Def).wrap_class() () at /home/pi/.dub/packages/pyd-0.9.9/pyd/infrastructure/pyd/class_wrap.d:1565
#5  0x000523b4 in pyd.class_wrap.wrap_class!(pyd.make_object.RangeWrapper, pyd.def.ModuleName!("pyd").ModuleName, pyd.class_wrap.Def!(pyd.make_object.RangeWrapper.iter(), pyd.def.PyName!("__iter__").PyName).Def, pyd.class_wrap.Def!(pyd.make_object.RangeWrapper.next()).Def).wrap_class() () at /home/pi/.dub/packages/pyd-0.9.9/pyd/infrastructure/pyd/class_wrap.d:1476
#6  0x00052388 in pyd.make_object.init_rangewrapper().__lambda2() () at /home/pi/.dub/packages/pyd-0.9.9/pyd/infrastructure/pyd/make_object.d:77
#7  0x0005b7cc in pyd.def.doActions(pyd.def.PyInitOrdering) (which=pyd.def.PyInitOrdering.After) at /home/pi/.dub/packages/pyd-0.9.9/pyd/infrastructure/pyd/def.d:395
#8  0x0005b6d8 in pyd.def.py_init() () at /home/pi/.dub/packages/pyd-0.9.9/pyd/infrastructure/pyd/def.d:287
#9  0x0005e398 in D main () at /home/pi/components/simple-python/source/app.d:127
```

it crashes on `py_init();`

### PR DESCRIPTION
**Pull request by WebFreak001**
fix #73

### CODE REVIEW

**Comment by ariovistus** [comment]
anybody know how to set build mode in appveyor? I tried setting it in the UI, but I guess it's being ignored because I'm using the yaml file?

I'm getting

The build phase is set to "MSBuild" mode (default), but no Visual Studio project or solution files were found in the root directory. If you are not building Visual Studio project switch build mode to "Script" and provide your custom build command

and can't find any docs on it

**Comment by WebFreak001** [comment]
why not base it off libdparse? https://github.com/dlang-community/libdparse/blob/master/appveyor.yml

**Comment by WebFreak001** [comment]
you should really squash this before merging

**Comment by WebFreak001** [comment]
does it only build or does it test now too?

**Comment by ariovistus** [comment]
you might want to unsubscribe from this pr, i'll be screwing with it for a while

**Comment by WebFreak001** [comment]
ping me when you are done then pls

**Comment by ariovistus** [comment]
Well, appveyor is nominally working, kind of, and I managed to validate win64 at least. pydexe command is broken in win64, so I don't want to release until I've figured out how to fix it. Have I mentioned I hate windows?

**Comment by WebFreak001** [comment]
same lol

**Pull request merged**
