### PR TITLE
Travis tests

### PR DESCRIPTION
**Pull request by John-Colvin**
Trying to improve the auto-testing.

@ariovistus would be you be able to take a look at the errors that have occured in the dmd-2.69.0-rc1 tests please (https://travis-ci.org/ariovistus/pyd/jobs/87949817)? There seems to be some problem with linking to expat and it's a bit beyond my understanding of python.

P.S. I have the commits from https://github.com/ariovistus/pyd/pull/35 in here as well.

### CODE REVIEW

**Comment by ariovistus** [comment]
never really been happy with travis for testing pyd, don't know why I even have it (quick checking prs i guess).

fyi there is a bamboo instance at https://pythond.atlassian.net/builds/allPlans.action, which until recently has been working. Stinker racked up 400 hours testing one commit and never actually finished any test.

**Comment by John-Colvin** [comment]
It's very nice to be able to have pull requests checked like this, especially for small changes.

I've tracked down the linking problem: get_config_var("LIBS") is giving libs in the wrong order, which in the end causes linking to fail. libexpat ends up before libpython, it should actually be after.

**Comment by ariovistus** [comment]
osx tests aren't working

**Comment by ariovistus** [comment]
dmd 2.067 and lower images aren't built properly for shared libraries. fix is simple:
ln -sT libphobos2.so libphobos2.so.0.67
in ~/dmd2/linux/lib64

not sure what the best way to do this in travis is

**Comment by ariovistus** [comment]
ldc images aren't build with shared library support and so are unsuitable for building python extensions.

**Comment by ariovistus** [comment]
gdc has always been unsuitable for building python extensions

**Pull request merged**
