### PR TITLE
Add windows 64-bit libs for 3.6

### PR DESCRIPTION
**Pull request by thewilsonator**
Please let me know what I should do w.r.t tests

Thanks 

see also #67

### CODE REVIEW

**Comment by ariovistus** [comment]
I don't have ci set up for windows, so no tests necessary

**Comment by thewilsonator** [comment]
Do you want me to set up a windows CI?

**Comment by ariovistus** [comment]
sure. I'm currently using travis (its free), what would you be using?
Actually, come to think of it, travis has docker support nowadays, I could have tests for more than just ubuntu again.

What issues are you having with pyd and 3.6? Seems like if you call it with python 3, it will use python 3, e.g. `py -3 setup.py pydexe` for the pyind example

**Comment by wilzbach** [comment]
> sure. I'm currently using travis (its free), what would you be using?

AppVeyor is free & simple to use. See e.g.
- https://github.com/dlang-community/DCD/blob/master/appveyor.yml
- https://github.com/libmir/mir-algorithm/blob/master/appveyor.yml

You just need to login at AppVeyor with your acocunt and add this project. Everything else is roughly similar to Travis.

**Pull request closed without merging**
